Feature/week2 examples
POCU/COMP2200CodeSamples pull request #2
Opened 2019-08-08 15:23 UTC by haydenhur

- Added week 2 code samples

2019-08-08 15:37 UTC, PenultimateWombat commented on 02/1_goto_statement/main.c
> +	goto begin;
indent consistantly

2019-08-08 15:38 UTC, PenultimateWombat commented on 02/1_goto_statement/main.c
> +		    }
indent

2019-08-08 15:40 UTC, PenultimateWombat commented on 02/2_array/main.c
> +	    average += grades[i];
indent

2019-08-08 15:48 UTC, PenultimateWombat commented on 02/5_static_keyword/external_file.c
> +#include <stdio.h>
why is this here?

2019-08-08 17:50 UTC, monkeywithbanana requested changes

2019-08-08 17:50 UTC, monkeywithbanana commented on 02/1_goto_statement/main.c
> +int bad_goto_statement_example(void)
come up with a better name. A function name should always start with a verb

2019-08-08 17:50 UTC, monkeywithbanana commented on 02/1_goto_statement/main.c
> +int good_goto_statement_example(void)
This is not a good example of a goto actually. Change this function to have 2 nested loop. There should be an if statement inside the nested loop that returns something from a condition. Else break out of the nested loop using a goto

2019-08-08 17:50 UTC, monkeywithbanana commented on 02/2_array/main.c
> +    int grades[5] = {70, 60, 85, 55, 90};
put a space between opening braces and the first element. Same with the closing braces

2019-08-08 17:50 UTC, monkeywithbanana commented on 02/3_multi_dimensional_array/main.c
> +    int grades[2][3] = {{65, 90, 75}, {70, 40, 50}};
space between opening/closing braces

2019-08-08 17:50 UTC, monkeywithbanana commented on 02/4_extern_keyword/external_file.c
> +int g_extern_var = 0;
let's add another global variable but this time don't use extern keyword. Comment this code out. In the codes slides, we can explain that if you uncomment this global variable, you will get compile error so try it out yourself

2019-08-11 18:11 UTC, popekim commented on 02/2_header/header.h
> +#ifndef HEADER_H
bad header file name.

2019-08-11 18:11 UTC, popekim commented on 02/2_header/header.h
> +#ifndef HEADER_H
use some real world example

2019-08-11 18:11 UTC, popekim commented on 02/2_header/header.h
> +int g_int_value = 0;
move this to .c file. this is not a right example for global variable...

this also doesn't prevent multiple global variable definitions in exe file

2019-08-11 18:11 UTC, popekim commented on 02/1_goto_statement/main.c
> +    end:
label should not be indented

2019-08-11 18:11 UTC, popekim commented on 02/1_goto_statement/main.c
> +        return 0;
so this one be indented

2019-08-11 18:11 UTC, popekim commented on 02/1_goto_statement/main.c
> +    end:
no indentation here

2019-08-11 18:11 UTC, popekim commented on 02/3_array/main.c
> +    printf("Average of all grades: %d\n", average);
"Average: "

2019-08-11 18:11 UTC, popekim commented on 02/4_multi_dimensional_array/main.c
> +    int grades[2][3] = {{ 65, 90, 75 }, { 70, 40, 50 }};
let's go multi line?

int grades[2][3] = {
   {},
   {},
};

2019-08-11 18:11 UTC, popekim commented on 02/4_multi_dimensional_array/main.c
> +    average /= i * j;
(i * j)

2019-08-11 18:11 UTC, popekim commented on 02/4_multi_dimensional_array/main.c
> +    printf("Average of all grades: %d\n", average);
"Average: %d"

2019-08-11 18:11 UTC, popekim commented on 02/5_extern_keyword/external_file.c
> +int g_extern_var = 0;
bad naming

2019-08-11 18:11 UTC, popekim commented on 02/5_extern_keyword/external_file.c
> +int g_extern_var = 0;
it is jus a global variable..

also try to use real world like examples.. 

this is not good code examples at all

2019-08-11 18:11 UTC, popekim commented on 02/5_extern_keyword/external_file.c
> +/*int g_var = 0;*/
why is this commented out?

2019-08-11 18:11 UTC, popekim commented on 02/5_extern_keyword/external_file.h
> +#ifndef EXTERNAL_FILE_H
also bad file name

2019-08-11 18:11 UTC, popekim commented on 02/6_static_keyword/external_file.c
> +static int s_static_var = 0;
real world example please

2019-08-11 18:11 UTC, popekim commented on 02/6_static_keyword/external_file.h
> +#ifndef EXTERNAL_FILE_H
bad header file name

2019-08-13 00:46 UTC, PenultimateWombat commented on 02/1_goto_statement/main.c
> +begin:
goto should only go downwards in code, not upwards

2019-08-13 05:31 UTC, monkeywithbanana requested changes

2019-08-13 05:31 UTC, monkeywithbanana commented on 02/1_goto_statement/main.c
> +int avoid_this_goto_statement(void)
Let's make this into a real world example too. Let's calculate a factorial given a count. Use while loop with bad goto examples.

2019-08-13 05:31 UTC, monkeywithbanana commented on 02/1_goto_statement/main.c
> +int use_this_goto_statement(void)
Let's do this instead. Pass in an 2D array and a number. You search for that number in the array.

Since we didn't go into multi dimensional arrays yet and how to pass in an array into the function yet, you can mention in the code slides that we will learn about arrays later

2019-08-13 05:31 UTC, monkeywithbanana commented on 02/2_header_and_source_file/main.c
> +    printf("g_dollars: %d\n", g_dollars);     /* 0 */
does this compile? You don't have extern keyword anywhere, (which you can't use in this example btw) so g_dollars shouldn't be accessible here

2019-08-13 05:31 UTC, monkeywithbanana commented on 02/2_header_and_source_file/main.c
> +    printf("g_dollars: %d\n", g_dollars);     /* 0 */
hmmm I guess it does work... but not sure if excluding extern keyword inside the header file if a variable declared inside it is being shared by multiple .c files....

https://stackoverflow.com/questions/1433204/how-do-i-use-extern-to-share-variables-between-source-files

2019-08-13 05:31 UTC, monkeywithbanana commented on 02/4_multi_dimensional_array/main.c
> +    { 65, 90, 75 },
indent 1 more

2019-08-13 05:31 UTC, monkeywithbanana commented on 02/4_multi_dimensional_array/main.c
> +    int grades[2][3] = {
2 and 3 are constants. Make proper const variables for these

2019-08-13 05:31 UTC, monkeywithbanana commented on 02/3_array/main.c
> +    int grades[5] = { 70, 60, 85, 55, 90 };
make const variable for 5

2019-08-13 05:31 UTC, monkeywithbanana commented on 02/5_extern_keyword/minion.h
> +void strengthen_minion(void);
go_berserk(void)

2019-08-13 05:31 UTC, monkeywithbanana commented on 02/5_extern_keyword/minion.h
> +
Add a seperate function `add_gold(int gold);`

2019-08-13 05:31 UTC, monkeywithbanana commented on 02/5_extern_keyword/minion.c
> +    g_gold += 10u;
remove this from here and use add_gold() function instead

2019-08-13 05:31 UTC, monkeywithbanana commented on 02/6_static_keyword/bank_account.h
> +
we need a static function example in here as well

2019-08-13 05:31 UTC, monkeywithbanana commented on 02/6_static_keyword/bank_account.h
> +
actually, static declaration would be in bank_account.c file tho

2019-08-13 05:31 UTC, monkeywithbanana commented on 02/6_static_keyword/bank_account.c
> +static unsigned int s_saving = 0u;
let's remove static from `s_saving`. Instead, have a  constant static variable `s_fee`. Every time there is a deposit to any account, you charge this fee. And you can make a static function to set the value of this fee.

2019-08-13 05:31 UTC, monkeywithbanana commented on 02/2_header_and_source_file/wallet.c
> +#include "wallet.h"
combine the definitions in this file with main.c and remove.

2019-08-13 05:31 UTC, monkeywithbanana commented on 02/2_header_and_source_file/wallet.c
> +void put_in_money(void)
take dollars and cents arguments

2019-08-13 05:31 UTC, monkeywithbanana commented on 02/2_header_and_source_file/wallet.c
> +void take_out_money(void)
take take dollars and cents arguments

2019-08-13 08:35 UTC, popekim requested changes

2019-08-13 08:35 UTC, popekim commented on 02/1_goto_statement/main.c
> +end:
name should be exit_loop; and shoudl have some more code before returning

2019-08-13 08:35 UTC, popekim commented on 02/2_header_and_source_file/wallet.c
> +int g_dollars = 0;
only extern is allowed in header file.

global variables go to .c file

2019-08-13 08:35 UTC, popekim commented on 02/2_header_and_source_file/wallet.c
> +void put_in_money(void)
put_in sounds weird. `deposit()`?

2019-08-13 08:35 UTC, popekim commented on 02/2_header_and_source_file/wallet.c
> +void take_out_money(void)
'withdraw()`?

2019-08-13 08:35 UTC, popekim commented on 02/2_header_and_source_file/wallet.c
> +    if (g_dollars != 0) {
>= 10

2019-08-13 08:35 UTC, popekim commented on 02/2_header_and_source_file/wallet.c
> +    if (g_cents > 0.0f) {
>= 0.25f

2019-08-13 08:35 UTC, popekim commented on 02/2_header_and_source_file/wallet.c
> +int g_dollars = 0;
https://stackoverflow.com/questions/8108634/global-variables-in-header-file/8108758

especially 3rd naswer

2019-08-13 15:00 UTC, haydenhur commented on 02/3_array/main.c
> +    int grades[5] = { 70, 60, 85, 55, 90 };
I get a compiler error for doing this(variable length array). Apparently, it's c99 feature

2019-08-13 15:00 UTC, haydenhur commented on 02/3_array/main.c
> +    int grades[5] = { 70, 60, 85, 55, 90 };
I think we gotta use 1) macro (like #define N (5). so int grades[N] = ..) or 2) just constants like above

2019-08-13 17:47 UTC, monkeywithbanana approved these changes

2019-08-14 05:15 UTC, popekim approved these changes

2019-08-14 05:15 UTC, popekim commented on 02/1_goto_statement/main.c
> +                goto exit_loop;
goto found:

2019-08-14 05:15 UTC, popekim commented on 02/1_goto_statement/main.c
> +    /* if n is not found in arr */
not_found:

and remove the comment

2019-08-14 05:15 UTC, popekim commented on 02/1_goto_statement/main.c
> +
return;

2019-08-14 05:15 UTC, popekim commented on 02/1_goto_statement/main.c
> +    printf("Number not found");
"%d not found", n

2019-08-14 05:15 UTC, popekim commented on 02/1_goto_statement/main.c
> +void find_number_in_2d_array(int arr[3][3], const int n)
find_number()

2019-08-14 05:15 UTC, popekim commented on 02/1_goto_statement/main.c
> +exit_loop:
found:

2019-08-14 05:15 UTC, popekim commented on 02/2_header_and_source_file/main.c
> +float g_cents = 0.0f;
cents is not float. cents is always unsigned integer..

2019-08-14 05:15 UTC, popekim commented on 02/1_goto_statement/main.c
> +
add comments saying it's a bad practice

2019-08-14 05:15 UTC, popekim commented on 02/1_goto_statement/main.c
> +    goto begin_loop;
add an empty line above

2019-08-14 05:15 UTC, popekim commented on 02/4_multi_dimensional_array/main.c
> +    int grades[2][3] = {
in c this is where u would use define at the top of a .c file

#define NUM_CLASSES (2)
#define NUM_SUBJECTS (3)

i briefly talked about #define during week 1. and it's probably a good palce to talk about it unofficially again in code slides

2019-08-14 05:15 UTC, popekim commented on 02/5_extern_keyword/main.c
> +    /* below does not compile */
`below code does not compile` or `this does not compile`

2019-08-14 05:15 UTC, popekim commented on 02/5_extern_keyword/main.c
> +    /* below does not compile */
same

2019-08-14 05:15 UTC, popekim commented on 02/6_static_keyword/bank_account.c
> +    g_chequing += (deposit - s_fee);
this could underflow. add comment and explain in code slides

2019-08-14 05:15 UTC, popekim commented on 02/6_static_keyword/bank_account.c
> +static void set_fee(int fee)
const int fee....

(fee can be negative? weird)

2019-08-14 05:15 UTC, popekim commented on 02/6_static_keyword/bank_account.h
> +void deposit_into_chequing(const unsigned int deposit);
deposit -> amount

2019-08-14 05:15 UTC, popekim commented on 02/6_static_keyword/bank_account.h
> +void deposit_into_saving(const unsigned int deposit);
deposit -> amount

2019-08-14 05:15 UTC, popekim commented on 02/6_static_keyword/main.c
> +    /* below causes a linker error */
/* this is a linker error */

2019-08-14 05:15 UTC, popekim commented on 02/6_static_keyword/main.c
> +    /* below causes a linker error */
/* this is a linker error */

2019-08-14 05:15 UTC, popekim commented on 02/6_static_keyword/main.c
> +    /* below causes a linker error */
/* this is a linker error */

2019-08-14 10:27 UTC, merged